/*********************************************
 *
 * Mentz 'Hello, World!' solution class
 *
 *
 *********************************************/
public with sharing class HelloWorld 
{
    public HelloWorld() 
    {

    }

    public String sayHelloWorld()
    {
        // change this method to return Hello, World!
        return null;
    }

    public String sayHelloWorldAndMore(String more)
    {
        // change this method to combine Hello, World! 
        // and the more parameter and return the result
        return null;
    }
}
